### ISSUE TITLE
Selection

### ISSUE THREAD

**Issue by hadim** [gillius/jfxutils#12]
Is that possible to dynamically select points in a chart in order to edit or remove it ?

If not, do you know any other Java plot library that can handle this ? (using JavaFX preferably)

Thanks

**Comment by gforman44** [comment]
Sorry, hadim, I don't know any library that supports this.  You'll probably have to listen for a mouse click, then convert the screen x,y coordinates to graph coordinates, then find the CLOSEST point (don't worry about speed-- people don't click that often), and if it's within a happy radius, then enable your edit/delete code.

  -G

**Comment by hadim** [comment]
Ok the old way then... :-(

Thank you for the information.

**Comment by gillius** [comment]
PRs for utility methods to do that are welcome. I'm not actively working the project anymore but I can promise to review and merge them in a timely manner.

**Comment by hadim** [comment]
I promise nothing but if I develop something like that I'll try to submit a PR.
