### ISSUE TITLE
Zooming with mouse drag from right to left

### ISSUE THREAD

**Issue by Jeredriq** [gillius/jfxutils#19]
Hi, 

My application can zoom when primary mouse key is pressed, dragged right side of the screen and released and it draws a rectangle to show the area it'll zoom. 

But whenever I try to do this from right to lleft, nothing happens.
What may be the cause?

Edit: Checked the demo for jfxutils, it has the same issue. How can I fix this?

**Comment by gillius** [comment]
I don't see a reason for this other than not implementing the code to properly handle the Rectangle in ChartZoomManager. A Rectangle has x, y, width, height. Logic would be needed to know whether to adjust x/y, or both x/y and width/height. I used property binding to keep it easier.

The methods that would need to change are start, onMousePressed, onMouseDragged, and onMouseReleased.

**Comment by Jeredriq** [comment]
The thing is I cant do the motion I've told in org.gillius.jfxutils.examples.Charting too. And I'm looking for a way to do this.

Maybe I didnt tell what happens quite right, lets say I pressed left mouse key at 346,368 coordinates. If I drag it to 400,400 It works without any problem but if I try to drag them to  300,368 / 346,300 / 300,300 it does not zoom.

I believe there is a check whether its positive distance for drawing the rectangle and zooming but sadly I couldnt find it

**Comment by Jeredriq** [comment]
Thanks, I'll try to fix it and whenever I can, I'll send a PR
