### ISSUE TITLE
JfxUtils utilization, intercept zoom event.

### ISSUE THREAD

**Issue by Alcariin** [gillius/jfxutils#3]
Hello, I wondering myself, how it was possible to intercept the zoom utilisation (wheel mouse or by using the rectangle) because after the new layout, I need to update my labels' positions. So initially I put a listener on the yAxis upper bound, but it generates some display issues. If you have any idea?

Anyway thank you a lot for this great library.

Thomas

**Comment by brcolow** [comment]
````java
rect.addListener(ScrollEvent.SCROLL, (event) -> {
    System.out.println(event);
});
````

**Comment by Alcariin** [comment]
Hi, thanks for your answer but in which file, do you pu this code?
I tried in JFXChartUtil file but the ScrollEvent is undefined for the type Rectangle and I guess rect is selectRect for Rectangle.

**Comment by brcolow** [comment]
In ChartZoomManager.java, after line 175, try this:

````java
handlerManager.addEventHandler( alse, ScrollEvent.SCROLL, (event) -> {
    System.out.println(event);
} );
````

**Comment by Alcariin** [comment]
It works only to intercept scroll event but I use onMouseRealeased() to intercept zoom from the rectangle. My real issue was how communicate with my controller but I uses a singleton and it works fine. Thanks

**Comment by gillius** [comment]
Is this still an issue? It seems that listening to the axis bound changes should work as this is how the zoom manager manipulates the chart. But, you'd have to listen to all of the 4 bounds to be sure that you've gotten all of the changes since it's possible to just zoom one axis or the other.
