### ISSUE TITLE
http://www.gillius.org/maven2 Forbidden

### ISSUE THREAD

**Issue by DigitalArcSystems** [gillius/jfxutils#8]
Unable to utilize maven repository because http://www.gillius.org/maven2 is forbidden.

**Comment by gillius** [comment]
The only thing that is forbidden is directory listings, which is true across my whole server. It should not prevent downloads and I also don't believe that should impact the ability to proxy from a manager like Nexus OSS. For example I can access these links:

http://gillius.org/maven2/org/gillius/jfxutils/maven-metadata.xml
http://gillius.org/maven2/org/gillius/jfxutils/0.4-SNAPSHOT/maven-metadata.xml
http://gillius.org/maven2/org/gillius/jfxutils/0.4-SNAPSHOT/jfxutils-0.4-20160511.022320-4.jar (latest snapshot)
http://gillius.org/maven2/org/gillius/jfxutils/0.3/jfxutils-0.3.jar (latest release)

My goal in the near term is to deploy to the central repository so my repo isn't needed anymore. I might also make a 1.0 release after cleaning some issues from recent changes (#4 and #5).

Do you have an example from mvn command line where it tries to hit a specific URL that it cannot access? As far as I know all that's needed is the maven-metadata.xml and artifacts themselves.

**Comment by gillius** [comment]
I have set up an account on the Central Repository now and 1.0-SNAPSHOT is deployed there. If you are using the latest jfxutils code (it is stable) then let me know if you can access the snapshot from there. Soon I plan on putting the 0.3 release up and 1.0 as well when 1.0 is ready.

**Comment by gillius** [comment]
0.3.1 is now released to Maven Central with the same code as 0.3.0. Now that the latest release and snapshot versions are available there, there is no longer a need for Gillius.org repository.
